[package]
name = "tokio-tungstenite"
description = "Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming", "asynchronous", "concurrency"]
keywords = ["websocket", "io", "web"]
authors = ["Daniel Abramov <dabramov@snapview.de>", "Alexey Galakhov <agalakhov@snapview.de>"]
license = "MIT"
homepage = "https://github.com/snapview/tokio-tungstenite"
documentation = "https://docs.rs/tokio-tungstenite/0.2.1"
repository = "https://github.com/snapview/tokio-tungstenite"
version = "0.2.1"

[features]
default = ["connect", "tls"]
connect = ["tokio-dns-unofficial", "tokio-core", "stream"]
tls = ["tokio-tls", "native-tls", "stream"]
stream = ["bytes"]

[dependencies]
futures = "0.1.13"
tokio-io = "0.1.1"
tungstenite = "0.2.4"
url = "1.4.0"

[dependencies.bytes]
optional = true
version = "*"

[dependencies.native-tls]
optional = true
version = "*"

[dependencies.tokio-dns-unofficial]
optional = true
version = "*"

[dependencies.tokio-core]
optional = true
version = "*"

[dependencies.tokio-tls]
optional = true
version = "*"

[dev-dependencies]
tokio-core = "0.1.7"

