[package]
name = "tokio-tungstenite"
version = "0.1.0"
authors = ["Daniel Abramov <dabramov@snapview.de>"]

[dependencies]
futures = "*"
tokio-core = "*"

tungstenite = { path = "../tungstenite-rs" }
