[package]
name = "tokio-tungstenite"
version = "0.1.0"
authors = ["Daniel Abramov <dabramov@snapview.de>"]

[dependencies]
futures = "*"
tokio-core = "*"
url = "*"

tungstenite = { git = "ssh://git@bitbucket.org/mikogo/tungstenite-rs.git" }

