[package]
name = "tokio-tungstenite"
description = "Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming", "asynchronous", "concurrency"]
keywords = ["websocket", "io", "web"]
authors = ["Daniel Abramov <dabramov@snapview.de>", "Alexey Galakhov <agalakhov@snapview.de>"]
license = "MIT"
homepage = "https://github.com/snapview/tokio-tungstenite"
documentation = "https://docs.rs/tokio-tungstenite"
repository = "https://github.com/snapview/tokio-tungstenite"
version = "0.1.3"

[dependencies]
futures = "*"
tokio-io = "*"
tungstenite = "0.2.0"
url = "*"

[dev-dependencies]
tokio-core = "*"
