name: CI

on: [push, pull_request]

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Install dependencies
        run: sudo apt-get install libssl-dev

      - name: Check no-default-features
        run: cargo check --no-default-features

      - name: Check default-features
        run: cargo check

      - name: Check native-tls
        run: cargo check --features native-tls

      - name: Check rustls
        run: cargo check --features rustls-tls

      - name: Check native-tls and rustls
        run: cargo check --features native-tls,rustls-tls

      - name: Test
        run: cargo test --release

  autobahn:
    name: Autobahn tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Install and configure docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Running Autobahn TestSuite for client
        run: ./scripts/autobahn-client.sh

      - name: Running Autobahn TestSuite for server
        run: ./scripts/autobahn-server.sh
